services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app

  composer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["composer"]

  semgrep-sec:
    image: semgrep/semgrep:latest
    volumes:
      - .:/src
    working_dir: /src
    entrypoint: ["semgrep"]
    command: ["scan", "--config", "p/phpcs-security-audit", "--config", "p/security-audit", "--error"]
