services:
    _defaults:
        autowire:      true
        autoconfigure: true

    Psr\Log\LoggerInterface:
        alias: monolog.logger.contao

    HeimrichHannot\FlareBundle\:
        resource: ../src
        exclude:
            - ../src/{Collection,Contao,ContaoManager,Contract,DependencyInjection,Dto,Engine,Event,Integration,Model,Trait,Util}
            - ../src/{Filter,Form,InferPtable,List,Paginator,Query,Sort,Specification}/*.php
            - ../src/Registry/Descriptor

    HeimrichHannot\FlareBundle\Engine\:
        resource: ../src/Engine
        exclude:
            - ../src/Engine/Engine.php
            - ../src/Engine/Context/*.php
            - ../src/Engine/Loader
            - ../src/Engine/View

    HeimrichHannot\FlareBundle\Filter\Resolver\FilterInvokerResolver:
        arguments:
            $invokerLocator: null # populated by compiler pass

    # Util classes registered as twig globals must be defined as services
    HeimrichHannot\FlareBundle\Util\Env: ~
    HeimrichHannot\FlareBundle\Util\Str: ~

#    bind:
#      $projectDir: '%kernel.project_dir%'
#      $csrfTokenName: '%contao.csrf_token_name%'
#      $kernelBundles: '%kernel.bundles%'
